//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyFinance2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FamilyFinance2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CASE WHEN Account.creditDebit = 0 THEN lSum.credit - lSum.debit ELSE lSum.debit - lSum.credit END 
        ///FROM Account 
        ///	INNER JOIN (
        ///		SELECT accountID, 
        ///			   SUM(CASE WHEN LineItem.creditDebit = 0 THEN LineItem.amount ELSE 0 END) AS credit, 
        ///			   SUM(CASE WHEN LineItem.creditDebit = 1 THEN LineItem.amount ELSE 0 END) AS debit
        ///		FROM LineItem 
        ///		WHERE accountID = 5
        ///		GROUP BY accountID ) AS lSum ON Account.id = lSum.accountID;
        ///
        ///--@ AND typeID = 5
        ///--@
        ///.
        /// </summary>
        internal static string AccountBalances {
            get {
                return ResourceManager.GetString("AccountBalances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT id, name
        ///FROM Account
        ///WHERE closed = 0 AND catagory = @@
        ///ORDER BY name;
        ///--@ 1 AND typeID = 12
        ///--@ 3
        ///-- 2 is not used its the real accounts.
        ///.
        /// </summary>
        internal static string AccountNames {
            get {
                return ResourceManager.GetString("AccountNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT AccountType.id, AccountType.name
        ///FROM AccountType INNER JOIN Account ON AccountType.id = Account.typeID
        ///WHERE Account.closed = 0 AND Account.catagory = 2
        ///ORDER BY AccountType.name;
        ///--@ 1
        ///--@ 2
        ///--@ 3.
        /// </summary>
        internal static string AccountTypes {
            get {
                return ResourceManager.GetString("AccountTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -------------------------------------------------------------------------------
        ///-------------------------------------------------------------------------------
        ///CREATE TABLE AccountType
        ///(
        ///	id					int				NOT NULL,
        ///	[name]				nvarchar(30)	NOT NULL,
        ///	CONSTRAINT PK_AccountType_id        PRIMARY KEY (id)
        ///);
        ///INSERT INTO AccountType VALUES (-1, &apos; &apos;); -- Null Account Type
        ///
        ///
        ///-------------------------------------------------------------------------------
        ///---------------------------------------------------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BuildTables {
            get {
                return ResourceManager.GetString("BuildTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE EnvelopeLine;
        ///DROP TABLE LineItem;
        ///DROP TABLE Envelope;
        ///DROP TABLE Account;
        ///DROP TABLE LineType;
        ///DROP TABLE EnvelopeGroup;
        ///DROP TABLE AccountType;
        ///
        ///
        ///
        ///.
        /// </summary>
        internal static string DropTables {
            get {
                return ResourceManager.GetString("DropTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT eSum.credit - eSum.debit
        ///FROM (
        ///	SELECT SUM(CASE WHEN LineItem.creditDebit = 0 THEN EnvelopeLine.amount ELSE 0 END) AS credit, 
        ///		   SUM(CASE WHEN LineItem.creditDebit = 1 THEN EnvelopeLine.amount ELSE 0 END) AS debit
        ///	FROM LineItem  
        ///		INNER JOIN EnvelopeLine ON LineItem.id = EnvelopeLine.lineItemID
        ///	WHERE EnvelopeLine.envelopeID = 25
        ///	GROUP BY EnvelopeLine.envelopeID ) AS eSum;
        ///
        ///--@ 52
        ///--@ .
        /// </summary>
        internal static string EnvelopeBalances {
            get {
                return ResourceManager.GetString("EnvelopeBalances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT g.id, g.name
        ///FROM EnvelopeGroup AS g INNER JOIN Envelope AS e ON g.id = e.groupID
        ///WHERE e.closed = 0 AND g.id &gt; -2
        ///ORDER BY g.name;
        ///.
        /// </summary>
        internal static string EnvelopeGroups {
            get {
                return ResourceManager.GetString("EnvelopeGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	Account.id, 
        ///		Account.name, 
        ///		Account.creditDebit, 
        ///		Account.envelopes, 
        ///		CASE WHEN lSum.credit = NULL THEN 0 ELSE lSum.credit END AS credit,
        ///		CASE WHEN lSum.debit = NULL THEN 0 ELSE lSum.debit END AS debit
        ///FROM Account LEFT OUTER JOIN (
        ///	SELECT accountID AS aID, 
        ///		SUM(CASE WHEN LineItem.creditDebit = 0 THEN LineItem.amount ELSE 0 END) AS credit, 
        ///		SUM(CASE WHEN LineItem.creditDebit = 1 THEN LineItem.amount ELSE 0 END) AS debit
        ///	FROM LineItem
        ///	WHERE accountID IN (SELECT id FROM Acco [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EnvelopeNames {
            get {
                return ResourceManager.GetString("EnvelopeNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT e.id, e.name, (elSum.credit - elSum.debit) AS balance
        ///FROM Envelope AS e INNER JOIN (
        ///	SELECT el.envelopeID AS eID, SUM(CASE WHEN l.creditDebit = 0 THEN el.amount ELSE 0 END) AS credit, SUM(CASE WHEN l.creditDebit = 1 THEN el.amount ELSE 0 END) AS debit
        ///	FROM LineItem AS l INNER JOIN EnvelopeLine AS el ON l.id = el.lineItemID
        ///	WHERE l.accountID = 25
        ///	GROUP BY el.envelopeID ) AS elSum ON e.id = elSum.eID
        ///WHERE e.closed = 0 AND elSum.credit &lt;&gt; elSum.debit
        ///ORDER BY e.name
        ///
        ///--@ 3
        ///--@ 
        ///.
        /// </summary>
        internal static string SubAccountBalances {
            get {
                return ResourceManager.GetString("SubAccountBalances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT id, name
        ///FROM Account
        ///WHERE closed = 0 AND catagory = @@
        ///ORDER BY name;
        ///--@ 1 AND typeID = 12
        ///--@ 3
        ///-- 2 is not used its the real accounts.
        ///.
        /// </summary>
        internal static string SubEnvelopeBalances {
            get {
                return ResourceManager.GetString("SubEnvelopeBalances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///-------------------------------------------------------------------------------
        ///-------------------------------------------------------------------------------
        ///--TABLE (id, name(30), typeID, catagory(1), closed(b), creditDebit(b), envelopes(b))
        ///INSERT INTO Account VALUES (101, &apos;Main Checking&apos;, 4, 2, 0, 1, 1);
        ///INSERT INTO Account VALUES (102, &apos;Vacation Savings&apos;, 5, 2, 0, 1, 1);
        ///INSERT INTO Account VALUES (103, &apos;Local Bank MC&apos;, 6, 2, 0, 0, 1);
        ///INSERT INTO Account VALUES (104, &apos;Car Loan&apos;, 3, 2, 0, 0, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestData {
            get {
                return ResourceManager.GetString("TestData", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap TLVBank {
            get {
                object obj = ResourceManager.GetObject("TLVBank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TLVEnvelope {
            get {
                object obj = ResourceManager.GetObject("TLVEnvelope", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TLVMoney {
            get {
                object obj = ResourceManager.GetObject("TLVMoney", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TLVRedFlag {
            get {
                object obj = ResourceManager.GetObject("TLVRedFlag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
